seed: 1
model:
    feature_extractor:
        arch: resnet50
        pretrained: true
    classifier:
        arch: mlpcls
        nonlinear: relu
        feat_size: [2048, 256] 
        n_class: 31 
data:
    source:
        loader: FileDataLoader
        data_root: /data/
        train: source.txt
        val: source.txt
        n_workers: 4
        drop_last: true
        n_class: 31 
        sampler:
            name: random
        imbalance_factor: 1
        reversed: false
        mode: exp
        inverse: false
        crop_size: 224
    target:
        loader: FileDataLoader
        data_root: /data/
        train: target.txt
        val: target.txt
        n_workers: 4
        drop_last: true
        n_class: 31 
        sampler:
            name: random
        imbalance_factor: 1
        reversed: false
        mode: exp
        inverse: false
        crop_size: 224
training:
    trainer: plain
    losses:
        loss_cls:
            name: cross_entropy
    iteration: 100004
    batch_size: 32
    val_interval: 5000
    save_interval: 10000
    print_interval: 2500
    optimizer:
        name: sgd
        momentum: 0.9
        weight_decay: 0.0005
        nesterov: true
    scheduler:
        init_lr: 0.003
        name: inv
        gamma: 0.001
        power: 0.75
    freeze_encoder: true
    pass_target: false
    resume:
        model: 
        load_cls: false
        param_only: true

